export const TYPES_FILTERS = {
  ALL: 'ALL',
  MOBILITY: 'MOBILITY',
  ABILITY: 'ABILITY',
  SCAVENGER: 'SCAVENGER',
  DEFENSE: 'DEFENSE',
  OFFENSE: 'OFFENSE',
  UTILITY: 'UTILITY',
  TALENT: 'TALENT',
  STAT: 'STAT'
} as const

export const AFFINITIES_FILTER = {
  ALL: 'ALL',
  REFLEX: 'REFLEX',
  BRAWN: 'BRAWN',
  DISCIPLINE: 'DISCIPLINE',
  FORTUNE: 'FORTUNE'
} as const
